"""add resume_embedding to candidates

Revision ID: 27c8d5cdc9dd
Revises: 9ff367c19072
Create Date: 2026-07-02 12:18:14.087957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c8d5cdc9dd'
down_revision: Union[str, Sequence[str], None] = '9ff367c19072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_embedding')
    # ### end Alembic commands ###
