"""make candidate fields nullable

Revision ID: 6a3e65dc2119
Revises: 709d78e3dab2
Create Date: 2026-06-30 21:05:03.448838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a3e65dc2119'
down_revision: Union[str, Sequence[str], None] = '709d78e3dab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'candidate_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('candidates', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('candidates', 'candidate_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
