"""change skills to json

Revision ID: 709d78e3dab2
Revises: 51160cf4af3a
Create Date: 2026-06-30 20:34:52.097366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '709d78e3dab2'
down_revision: Union[str, Sequence[str], None] = '51160cf4af3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'resume_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'resume_file_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('candidates', 'skills',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'skills',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('candidates', 'resume_file_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('candidates', 'resume_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
