"""increase recommendation column size

Revision ID: a29904ed20c9
Revises: a2c6a6c56542
Create Date: 2026-07-01 17:55:35.005937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a29904ed20c9'
down_revision: Union[str, Sequence[str], None] = 'a2c6a6c56542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_matches', 'recommendation',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint('uq_candidate_job', 'ai_matches', ['candidate_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_job', 'ai_matches', type_='unique')
    op.alter_column('ai_matches', 'recommendation',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
