"""update candidate model

Revision ID: c02a7790ac08
Revises: 6a3e65dc2119
Create Date: 2026-06-30 21:07:48.634751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c02a7790ac08'
down_revision: Union[str, Sequence[str], None] = '6a3e65dc2119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'resume_file_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('pdf', 'docx', name='resume_file_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'resume_file_type',
               existing_type=sa.Enum('pdf', 'docx', name='resume_file_type_enum'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
